### ISSUE TITLE
Creative Assignment 2 ready for grading

### ISSUE THREAD

**Issue by alex-cox-gsd** [VIS-2129-F2020/alexcox-vis#2]
Hello! Creative Assignment 2 is ready for finally ready for grading (I had some issues committing it last night, but it looks like it finally went through this morning). The HTML file can be found at https://vis-2129-f2020.github.io/alexcox-vis/Vis-Creative-Assignment-2.html. Thank you!

**Comment by bauranov** [comment]
Great work! Make sure to remove the messages and warnings from the HTML, but other than that, awesome job.
